<?php
/**
 * Magic Logix Gallery
 *
 * Provides an image gallery extension for Magento
 *
 * @category		MLogix
 * @package		Gallery
 * @author		Brady Matthews
 * @copyright		Copyright (c) 2008 - 2010, Magic Logix, Inc.
 * @license		http://creativecommons.org/licenses/by-nc-sa/3.0/us/
 * @link		http://www.magiclogix.com
 * @link		http://www.magentoadvisor.com
 * @since		Version 1.0
 *
 * Please feel free to modify or distribute this as you like,
 * so long as it's for noncommercial purposes and any
 * copies or modifications keep this comment block intact
 *
 * If you would like to use this for commercial purposes,
 * please contact me at brady@magiclogix.com
 *
 * For any feedback, comments, or questions, please post
 * it on my blog at http://www.magentoadvisor.com/plugins/gallery/
 *
 */
?><?php
$bcs = $this->getBreadcrumbs();

?>
<div class="gallerybc breadcrumbs">
	<div class="shadow">
		<div class="shadow_left">
			<div class="shadow_right">
				<div class="shadow_mid"></div>
			</div>
		</div>    	
	</div> 
	<div class="event_bc">
<img alt="event-icon" src="<?php echo $this->getSkinUrl('images/leaf.png') ?>">
<?php 


if($this->getCurrentEvents()->getId() > 0)
	echo '<a href="'.$this->getUrl('events').'">Events</a>'.' - ';
	
foreach($bcs as $bc)
{
	echo '<a href="'.$this->getViewUrl($bc->getId).'">'.$bc->getTitle().'</a>'.' - ';
}

echo  mb_substr($this->getEventsTitle(), 0,100)?>
	
	</div>
</div>