<?php
/**
 * ecomwebpro.com	
*/
?>


<?php
$items = $this->getEvents();

$cat_thumbWidth = 166;
$cat_thumbHeight = 166;

$thumbWidth = 107;
$thumbHeight = 80;

$numItems = 0;
$currentId = array();
?>

<link href="<?php echo $this->getSkinUrl('css/camera.css')?>" rel="stylesheet" type="text/css" />

<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/camera.min.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/jquery.easing.1.3.js') ?>"></script>
<div class="gallery_wrapper2">
<div class="event-categories">
<?php


if(count($items))
foreach($items as $item)
{

	if($item->hasChildren())
	{
?>	
<!-- LIST EVENT -->
<style>
.camera_wrap .camera_pag .camera_pag_ul{
display:none;
}
.camera_loader {
display:none;
}

.camera_target_content{
display:none;
}
</style>
<div class="event-category">
	<a href="<?=$this->getViewUrl($item->getId())?>" title="<?php echo $item->getTitle() ?>"><img width="<?=$cat_thumbWidth?>" height="<?=$cat_thumbHeight?>" src="<?=$item->getThumbnail($cat_thumbWidth,$cat_thumbHeight)?>" title="<?=$item->getTitle()?>" alt="<?=$item->getAlt()?>"/></a>
    <h2 class="product-name">
		<a href="<?=$this->getViewUrl($item->getId())?>" title="<?php echo $item->getTitle() ?>">
			<?php 
				$currentId[] = $item->getId();
				$dots = '';
				if(mb_strlen($item->getTitle()) > 70)
					$dots = '...';
		 	?>
			<?=mb_substr($item->getTitle(), 0,70) . $dots?>
		</a>
	</h2>
</div>

<?php
	}
	else $numItems++;
}
?>
		<div class="clearfix"></div>
</div>
    
    
    
<!-- DETAIL -->    
<?php if($numItems) { ?>
<div class="demo">

	<div id="slider">
		<?php
		if(count($items))
		foreach($items as $item)
		{
		
			if(!$item->hasChildren())
			{?>	
			<div data-src="<?=$item->getImageUrl()?>"></div>
		
			<?php
			}
		}
		?>
		
	</div>
	
	<br/>
	<div class="slide_desc">
		<?php if($this->getItemRelateData($this->getIdFromUrl(),'description')):?>
			<p><?php 
					$dots = '';
					if(mb_strlen($this->getItemRelateData($this->getIdFromUrl(),'description')) > 355){
						$dots = '...';
					}
					echo mb_substr($this->getItemRelateData($this->getIdFromUrl(),'description'), 0,342,'UTF-8') . $dots;?></p>
		<?php else:?>
			<p><?php echo 'Empty description';?></p>
		<?php endif;?>

		<div class="social"><!-- Hupso Share Buttons - http://www.hupso.com/share/ --><div class="hupso-share-buttons" ><a class="hupso_toolbar" href="http://www.hupso.com/share/"><img src="http://static.hupso.com/share/buttons/share-medium.png" style="border:0px; padding-top:5px; float:left;" alt="Share Button"/></a><script type="text/javascript">var hupso_services_t=new Array("Pinterest","Twitter","Facebook","Google Plus","StumbleUpon","Tumblr","Digg","Delicious");var hupso_toolbar_size_t="medium";</script><script type="text/javascript" src="http://static.hupso.com/share/js/share_toolbar.js"></script></div><!-- Hupso Share Buttons --></div>
		
	</div>
	
	<div class="space_block"></div>
	
	<?php 
	$relateItems = $this->getEventsRelate();
	$randItems = array();
	if(!$item->hasChildren()){
		
		foreach($relateItems as $rItem){
			if($rItem['parent_id'] == 0){
	 			$randItems[] = $rItem['events_id'];
			}
	 }
	 
	$itemRelate = array_rand($randItems,5);
	?>
	<div class="relate_project">
		<div class="event_bc">
			<img alt="event-icon" src="<?php echo $this->getSkinUrl('images/leaf.png') ?>">	
			Relate project
		</div>
		<?php for($i=0;$i<5;$i++){?>
		<?php $rFileName = $this->getItemRelateData($randItems[$itemRelate[$i]],'filename');?>
			<div class="event-category">
				<a href="<?=$this->getViewUrl($randItems[$itemRelate[$i]])?>" name = "events_id"><img width="<?=$cat_thumbWidth?>" height="<?=$cat_thumbHeight?>" src="<?php echo $this->getRelateThumbnail($cat_thumbWidth ,$cat_thumbHeight,$randItems[$itemRelate[$i]],$rFileName)?>" title="<?=$this->getItemRelateData($randItems[$itemRelate[$i]],'item_title')?>" alt="<?=$this->getItemRelateData($randItems[$itemRelate[$i]],'alt')?>"/></a>
			    <h2 class="product-name"><a href="<?=$this->getViewUrl($randItems[$itemRelate[$i]])?>">
			<?php $dots = '';
				if(mb_strlen($this->getItemRelateData($randItems[$itemRelate[$i]],'item_title')) > 70)
					$dots = '...';
		 	?>
		<?=mb_substr($this->getItemRelateData($randItems[$itemRelate[$i]],'item_title'), 0,70).$dots?></a></h2>
			</div>
		<?php } ?>	
	</div>
	<?php }?>
</div>

<div class="clearfix"></div>
<script type="text/javascript">
	jQuery.noConflict();
	jQuery(document).ready(function(){
		jQuery('#slider').camera({
			autoAdvance: false
		});
	});
</script>
<?php } ?>
</div>
