<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage_Payone
 * @copyright  Copyright (c) 2009 Phoenix Medien GmbH & Co. KG (http://www.phoenix-medien.de)
 */
?>
<b><?php echo Mage::helper('payone')->__('You will be redirected to Payone in a few seconds.'); ?></b>
<?php $_formData = $this->getFormData() ?>
<?php if (!empty($_formData)): ?>
<form name="payone" id="payone_payment_form" action="<?php echo $this->getFormAction();?>" method="<?php echo $this->sendPost() ? 'POST' : 'GET'; ?>">
    <?php foreach ($_formData as $name => $value): ?>
    	<?php if (is_array($value)): ?>
    		<?php foreach($value as $cnt => $arr_value): ?>
    			<input type="hidden" name="<?php echo $name.'['.$cnt.']'; ?>" value="<?php echo $this->htmlEscape($arr_value); ?>"/>
    		<?php endforeach; ?>
    	<?php else: ?>
    	    <input type="hidden" id="<?php echo $name; ?>"  name="<?php echo $name; ?>" value="<?php echo $this->htmlEscape($value); ?>"/>
    	<?php endif; ?>
    <?php endforeach; ?>
</form>
<script type="text/javascript">
//<![CDATA[
    var paymentform = document.getElementById('payone_payment_form');
    window.onload = paymentform.submit();
//]]>
</script>
<?php else: ?>
<script type="text/javascript">
//<![CDATA[
    window.location.href = "<?php echo $this->getFormAction();?>";
//]]>
</script>
<?php endif; ?>