<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage_Payone
 * @copyright  Copyright (c) 2009 Phoenix Medien GmbH & Co. KG (http://www.phoenix-medien.de)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

$_code=$this->getMethodCode();
?>

<script type="text/javascript">
    if (window.Translator) {
        if (Translator.translate('Credit card number doesn\'t match credit card type') == 'Credit card number doesn\'t match credit card type') {
            Translator.add(<?php echo $this->jsTranslate('Credit card number doesn\'t match credit card type'); ?>);
        }
        if (Translator.translate('Card type doesn\'t match credit card number') == 'Card type doesn\'t match credit card number') {
            Translator.add(<?php echo $this->jsTranslate('Card type doesn\'t match credit card number'); ?>);
        }
    }
</script>

<fieldset class="form-list" id="fieldset_<?php echo $_code ?>">

<?php 
    $payoneCcSessionInfo = Mage::getSingleton('core/session')->getPayoneCcInfo();
    $isDataSaved = !empty($payoneCcSessionInfo);
    if (!$isDataSaved) {
        $payoneCcSessionInfo = array(
            'cc_owner' => '',
            'cc_type' => '',
            'cc_number' => '',
            'cc_exp_month' => '',
            'cc_exp_year' => '',
            'cc_additional_data' => ''
        );
    }
?>

<iframe frameborder="0" name="payment_form_<?php echo $_code ?>" id="payment_form_<?php echo $_code ?>" style="width:100%; height:300px; border:none; display:none;" src="<?php echo Mage::getUrl('payone/processing/ccform') ?>"></iframe>

<input type="hidden" name="payment[cc_owner]" value="<?php echo $payoneCcSessionInfo['cc_owner'] ?>" />
<input type="hidden" name="payment[cc_type]" value="<?php echo $payoneCcSessionInfo['cc_type'] ?>" />
<input type="hidden" name="payment[cc_number]" value="<?php echo $payoneCcSessionInfo['cc_number'] ?>" />
<input type="hidden" name="payment[cc_exp_month]" value="<?php echo $payoneCcSessionInfo['cc_exp_month'] ?>" />
<input type="hidden" name="payment[cc_exp_year]" value="<?php echo $payoneCcSessionInfo['cc_exp_year'] ?>" />
<input type="hidden" id="hidden_cc_additional_data" name="payment[cc_additional_data]" value="<?php echo $payoneCcSessionInfo['cc_additional_data'] ?>" />
</fieldset>
