<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage_Payone
 * @copyright  Copyright (c) 2009 Phoenix Medien GmbH & Co. KG (http://www.phoenix-medien.de)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php $_authorizeReport = $this->getAuthorizeReport(); ?>
<?php if (count($_authorizeReport) > 0 && $_authorizeReport['method_code'] == 'payone_vor'): ?>
    <?php echo $this->__('Please transfer %s to this bank account:', Mage::helper('core')->currency($_authorizeReport['amount'],true,false)) ?><br/>
    <?php echo $this->__('Payee: %s', $_authorizeReport['clearing_bankaccountholder']) ?><br/>
    <?php echo $this->__('Account number: %s', $_authorizeReport['clearing_bankaccount']) ?><br/>
    <?php echo $this->__('Bank sort code: %s', $_authorizeReport['clearing_bankcode']) ?><br/>
    <?php echo $this->__('IBAN: %s', $_authorizeReport['clearing_bankiban']) ?><br/>
    <?php echo $this->__('BIC: %s', $_authorizeReport['clearing_bankbic']) ?><br/>
    <?php echo $this->__('Bank: %s', $_authorizeReport['clearing_bankname']) ?><br/>
    <?php echo $this->__('Payment reference: %s', $_authorizeReport['txid']) ?><br/>
    <?php Mage::getSingleton('core/session')->setAuthorizeResponse($_authorizeReport); ?>
<?php else: ?>
    <?php echo $this->htmlEscape($this->getMethod()->getTitle()) ?><br />
    <?php
		if ($this->getInfo()->getLastTransId() == '') {
			echo $this->__('Payment has not been processed yet.') . '<br/>';
		} else {
			echo $this->__('Payone Transaction ID: %s', $this->htmlEscape($this->getInfo()->getLastTransId())) . '<br/>';
		}
	?>
<?php endif; ?>