<?php
/**
 * Magic Logix Gallery
 *
 * Provides an image gallery extension for Magento
 *
 * @category		MLogix
 * @package		Gallery
 * @author		Brady Matthews
 * @copyright		Copyright (c) 2008 - 2010, Magic Logix, Inc.
 * @license		http://creativecommons.org/licenses/by-nc-sa/3.0/us/
 * @link		http://www.magiclogix.com
 * @link		http://www.magentoadvisor.com
 * @since		Version 1.0
 *
 * Please feel free to modify or distribute this as you like,
 * so long as it's for noncommercial purposes and any
 * copies or modifications keep this comment block intact
 *
 * If you would like to use this for commercial purposes,
 * please contact me at brady@magiclogix.com
 *
 * For any feedback, comments, or questions, please post
 * it on my blog at http://www.magentoadvisor.com/plugins/gallery/
 *
 */
?>


<?php
$items = $this->getWedding();

$cat_thumbWidth = 133;
$cat_thumbHeight = 133;

$thumbWidth = 107;
$thumbHeight = 80;

$numItems = 0;
?>

<link href="<?php echo $this->getSkinUrl('css/camera.css')?>" rel="stylesheet" type="text/css" />

<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/camera.min.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/jquery.easing.1.3.js') ?>"></script>
<div class="gallery_wrapper2">



<div class="event-categories">
<?php


if(count($items))
foreach($items as $item)
{

	if($item->hasChildren())
	{
?>	
<!-- LIST EVENT -->
<style>
.camera_wrap .camera_pag .camera_pag_ul{
display:none;
}
.camera_loader {
display:none;
}

.camera_target_content{
display:none;
}
</style>
<div class="event-category">
	<a href="<?=$this->getViewUrl($item->getId())?>" title="<?php echo $item->getTitle() ?>"><img width="<?=$cat_thumbWidth?>" height="<?=$cat_thumbHeight?>" src="<?=$item->getThumbnail($cat_thumbWidth,$cat_thumbHeight)?>" title="<?=$item->getTitle()?>" alt="<?=$item->getAlt()?>"/></a>
    <h2 class="product-name">
		<a href="<?=$this->getViewUrl($item->getId())?>" title="<?php echo $item->getTitle() ?>">
			<?php 
				$dots = '';
				if(mb_strlen($item->getTitle()) > 70)
					$dots = '...';
		 	?>
			<?=mb_substr($item->getTitle(), 0,70) . $dots?>
		</a>
	</h2>
</div>

<?php
	}
	else $numItems++;
}
?>
		<div class="clearfix"></div>
</div>
    
    
    
<!-- DETAIL -->    
<?php if($numItems) { ?>
<div class="demo">
	<div id="slider">
		<?php
		if(count($items))
		foreach($items as $item)
		{
		
			if(!$item->hasChildren())
			{
			/*<img src="<?=$item->getImageUrl()?>" title="<?=$item->getTitle()?>" alt="<?=$item->getAlt()?>"/>*/
		?>	
		<div data-src="<?=$item->getImageUrl()?>"></div>
		
		<?php
			}
		}
		?>
	</div>
	
</div>
<div class="clearfix"></div>
<div class="hr-bottom"></div>

	
<script type="text/javascript">
	jQuery.noConflict();
	jQuery(document).ready(function(){
		jQuery('#slider').camera({
			autoAdvance: false
		});
	});
</script>
<?php } ?>
</div>