<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage_Payone
 * @copyright  Copyright (c) 2008 Phoenix Medien GmbH & Co. KG (http://www.phoenix-medien.de)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
$_code=$this->getMethodCode();
?>

<ul id="payment_form_<?php echo $_code ?>" style="display:none">
    <li>
        <div class="input-box">
            <label for="<?php echo $_code ?>_owner"><?php echo $this->__('Account holder') ?> <span class="required">*</span></label><br />
            <input type="text" title="<?php echo $this->__('Account holder') ?>" class="required-entry input-text" id="<?php echo $_code ?>_owner" name="payment[owner]" value="<?php echo $this->htmlEscape($this->getInfoData('cc_owner') ? $this->getInfoData('cc_owner') : $this->getBillingName()); ?>" />
        </div>
    </li>
    <li>
        <div class="input-box">
            <label for="<?php echo $_code ?>_account_number"><?php echo $this->__('Account number') ?> <span class="required">*</span></label><br />
            <input type="text" id="<?php echo $_code ?>_account_number" name="payment[account_number]" title="<?php echo $this->__('Account number') ?>" class="validate-digits required-entry input-text" value="" autocomplete="off" maxlength="10"/>
        </div>
        <input type="hidden" name="payment[additional_data]" value="" />
    </li>
    <li>
        <div class="input-box">
            <label for="<?php echo $_code ?>_bank_code"><?php echo $this->__('Bank code') ?> <span class="required">*</span></label><br />
            <input type="text" id="<?php echo $_code ?>_bank_code" name="payment[bank_code]" title="<?php echo $this->__('Bank code') ?>" class="validate-digits required-entry input-text" value="" maxlength="10"/>
        </div>
    </li>
</ul>
