<?php $posts = $this->getPosts(); ?>

<div class="block block-blog">
    <div class="block-title">
    	<?php if($this->getCateIdFromUrl() == 'baochi'|| $this->getCateIdFromUrl() == 'xuatban' || $this->getCateIdFromUrl() == 'press' || $this->getCateIdFromUrl() == 'news' || $this->getCateIdFromUrl() == 'blog_link' ):?>
	        <strong>
		        <span class="title-left">
		        	<a href="<?php echo Mage::getBaseUrl();?>blog/cat/baochi"><?php echo Mage::helper('blog')->__('News'); ?></a>
		        </span>
	        </strong>
		         <span class="xb-title"></span>
		    <strong>
		    	<span class="title-right">&nbsp<img src = "<?php echo Mage::getBaseUrl();?>skin/frontend/default/default/aw_blog/images/icon_blog.png" />
		        	<a href="<?php echo Mage::getBaseUrl();?>blog/cat/xuatban/"><?php echo Mage::helper('blog')->__(' Xuất bản'); ?></a>
		        </span>
		    </strong>
        <?php endif;?>
        <?php if($this->getCateIdFromUrl() == 'new-design'):?>
        	<strong>
	        	<span>
	        		<?php echo Mage::helper('blog')->__('New Design'); ?>
	        	</span>
        	</strong>
        <?php endif;?>
    </div>
    
    <div class="saparate_title"></div>
    
</div>


<?php if(count($posts)): ?>
	<?php foreach ($posts as $post): ?>
<div class="postWrapper">
    <div class="postTitle">
        <h2><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle();?></a></h2>
		<h3 style="font-weight: normal;"><?php echo $post->getCreatedTime(); ?></h3>
    </div>
    <div class="postContent"><?php echo $post->getPostContent(); ?></div>
	<?php echo $this->getBookmarkHtml($post) ?>
	<div class="tags"><?php echo Mage::getBlockSingleton('blog/blog')->getTagsHtml($post) ?></div>
	<div class="postDetails">
		<?php if($this->getCommentsEnabled()): ?>
		<?php echo $post->getCommentCount(); ?> <a href="<?php echo $post->getAddress(); ?>#commentBox" >Comments</a> | 
		<?php endif; ?>
		<?php $postCats = $post->getCats(); ?>
		<?php if(!empty($postCats)):?>
			<?php echo Mage::helper('blog')->__('Posted in');?>
			<?php foreach($postCats as $title=>$url): ?>
				<a href="<?php echo $url; ?>"><?php echo $title; ?></a> 
			<?php endforeach;?> 
        <?php else:?>
        	 <?php echo Mage::helper('blog')->__('Posted');?>
        <?php endif;?><?php echo$this->__("By");?> <?php echo $post->getUser(); ?></div>
</div>
	<?php endforeach; ?>
<?php else: ?>  
<?php echo Mage::helper('blog')->__('No Posts in this Category.');?>
<?php endif; ?>
<?php $this->getPages(); ?>
