<?php 
	$catIdent = $this->getCategories()->getData('identifier');
	$cateFlag = false;
?>
<?php if($this->getCateIdFromUrl() == 'news' || $this->getCateIdFromUrl() == 'press' || $this->getCateIdFromIdentifier() == '3' || $this->getCateIdFromIdentifier() == '4'):?>
 <div class="block-title">
        <strong><span><?php echo Mage::helper('blog')->__('News about Padma de Fleur'); ?></span></strong>
 </div>
 <?php endif;?>
 
 <?php if($this->getCateIdFromUrl() == 'new-design' || $this->getCateIdFromIdentifier() == '2'):?>
 <div class="block-title">
        <strong><span><?php echo Mage::helper('blog')->__('New Design '); ?></span></strong>
 </div>
 <?php endif;?>
<div class="block block-blog">
	<div class="block-content">
<?php if ($posts = $this->getRecent()): ?>
	<div class="menu-recent">
		<!--<h5><?php echo Mage::helper('blog')->__('Recent Posts');?></h5>	-->
		<ul>
		<?php foreach ($posts as $post): ?>
			<li><a href="<?php echo $post->getAddress(); ?>" ><?php echo "<span class='recent_bullet'>.</span> ".$post->getTitle();?></a></li>
		<?php endforeach; ?>
       	</ul>
	</div>	
<?php endif; ?>
<?php //if($this->getCateIdFromUrl() == 'news' || $this->getCateIdFromUrl() == 'press' || $this->getCateIdFromUrl() == 'blog_link'):?>
	<?php //if($this->getCategories()->count() && Mage::getStoreConfig('blog/menu/category')): ?>  
		<!--<div class="menu-categories">
	        <h5><?php //echo Mage::helper('blog')->__('Categories');?></h5>
	        <ul>
	<?php //$cats = $this->getCategories(); ?>

	<?php //foreach ($cats as $cat): ?>
	
	
	<?php //if($cat->getId() != '2' && $cat->getId() != '3'):?>
			<li><a href="<?php//echo $cat->getAddress(); ?>" ><?php //echo $cat->getTitle();?></a></li>
	<?php //endif;?>
	<?php //endforeach;?>
	    	</ul>
		</div>	
	<?php //endif;  ?>
<?php //endif;  ?>		
		


<?php //echo $this->getChildHtml('blog_tags');?>-->
	</div>
</div>
